{
 "title": "OpenStack Nova",
 "tags": [ "openstack" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(openstack_identity_up{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(openstack_identity_up{job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Nova service", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Nova status",
   "type": "stat",
   "description": "Reports the status of the Nova compute service.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "openstack_nova_up{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "VMs",
   "type": "timeseries",
   "description": "The current number of total and running virtual machines.",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openstack_nova_total_vms{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Instance usage",
   "type": "timeseries",
   "description": "Percentage of the maximum number of instances in use for each project.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "openstack_nova_limits_instances_used{job=~\"$job\",instance=~\"$instance\"} / clamp_min(openstack_nova_limits_instances_max{job=~\"$job\",instance=~\"$instance\"}, 1)",
     "legendFormat": "{{instance}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "VCPU usage",
   "type": "timeseries",
   "description": "Percentage of the maximum number of virtual CPUs in use for each project.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "openstack_nova_limits_vcpus_used{job=~\"$job\",instance=~\"$instance\"} / clamp_min(openstack_nova_limits_vcpus_max{job=~\"$job\",instance=~\"$instance\"}, 1)",
     "legendFormat": "{{instance}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Percentage of the maximum amount of memory in use for each project.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "openstack_nova_limits_memory_used{job=~\"$job\",instance=~\"$instance\"} / clamp_min(openstack_nova_limits_memory_max{job=~\"$job\",instance=~\"$instance\"}, 1)",
     "legendFormat": "{{instance}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "Agents",
   "type": "table",
   "description": "Details for the agents for OpenStack Nova.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "openstack_nova_agent_state{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{service}} - {{hostname}}"
    }
   ]
  }
 ]
}