{
 "title": "OpenStack Cinder",
 "tags": [ "openstack" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(openstack_identity_up{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(openstack_identity_up{job=~\"$job\"}, instance)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Cinder service", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Cinder status",
   "type": "stat",
   "description": "Reports the status of the Cinder block storage service.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "openstack_cinder_up{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "timeseries",
   "description": "The number of volumes managed by Cinder.",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openstack_cinder_volumes{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Volume status",
   "type": "timeseries",
   "description": "The current status of volumes in Cinder.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "\n  openstack_cinder_volume_status_counter{job=~\"$job\",instance=~\"$instance\", status=~\"error|error_backing-up|error_deleting|error_extending|error_restoring\"}\n > 0",
     "legendFormat": "{{instance}} - {{status}}"
    },
    {
     "expr": "topk(5, \n  openstack_cinder_volume_status_counter{job=~\"$job\",instance=~\"$instance\", status!~\"error|error_backing-up|error_deleting|error_extending|error_restoring\"}\n) > 0",
     "legendFormat": "{{instance}} - {{status}}"
    }
   ]
  },
  {
   "title": "Volume usage",
   "type": "timeseries",
   "description": "The percent of volume storage in use for Cinder.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "openstack_cinder_limits_volume_used_gb{job=~\"$job\",instance=~\"$instance\"} / clamp_min(openstack_cinder_limits_volume_max_gb{job=~\"$job\",instance=~\"$instance\"}, 1)",
     "legendFormat": "{{instance}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "Backup usage",
   "type": "timeseries",
   "description": "The percent of backup storage in use for Cinder.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "openstack_cinder_limits_backup_used_gb{job=~\"$job\",instance=~\"$instance\"} / clamp_min(openstack_cinder_limits_backup_max_gb{job=~\"$job\",instance=~\"$instance\"}, 1)",
     "legendFormat": "{{instance}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "Pool usage",
   "type": "timeseries",
   "description": "The percent of pool capacity in use for Cinder.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(openstack_cinder_pool_capacity_total_gb{job=~\"$job\",instance=~\"$instance\"} - openstack_cinder_pool_capacity_free_gb{job=~\"$job\",instance=~\"$instance\"}) / clamp_min(openstack_cinder_pool_capacity_total_gb{job=~\"$job\",instance=~\"$instance\"}, 1)",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "timeseries",
   "description": "The number of volume snapshots in Cinder.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "openstack_cinder_snapshots{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Agents",
   "type": "table",
   "description": "Details for the agents for OpenStack Cinder.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "openstack_cinder_agent_state{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} - {{service}} - {{hostname}}"
    }
   ]
  }
 ]
}