{
 "title": "Velero cluster view",
 "tags": [ "velero" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Prometheus data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(velero_backup_success_total{job=\"integrations/velero\"}, job)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(velero_backup_success_total{job=\"integrations/velero\",job=~\"$job\"}, cluster)"
   },
   { "name": "loki_datasource", "label": "Loki data source", "query": "loki" },
   {
    "name": "top_cluster_count",
    "label": "Top cluster count",
    "query": "2 : 2,4 : 4,6 : 6,8 : 8,10 : 10"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Successful backups / $__interval",
   "type": "stat",
   "description": "Number of successful backups across all clusters.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (\n  increase(velero_backup_success_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "Backups"
    }
   ]
  },
  {
   "title": "Failed backups / $__interval",
   "type": "stat",
   "description": "Number of failed backups across all clusters",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (\n  increase(velero_backup_failure_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "Backups"
    }
   ]
  },
  {
   "title": "Successful restores / $__interval",
   "type": "stat",
   "description": "Number of successful restores across all clusters.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (\n  increase(velero_restore_success_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "Restores"
    }
   ]
  },
  {
   "title": "Failed restores / $__interval",
   "type": "stat",
   "description": "Number of failed restores across all clusters.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (\n  increase(velero_restore_failed_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)",
     "legendFormat": "Restores"
    }
   ]
  },
  {
   "title": "Velero alerts",
   "type": "alertlist",
   "description": "Status of firing alerts for Velero.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 }
  },
  { "title": "Top clusters", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 5 } },
  {
   "title": "Top clusters by backups / $__interval",
   "type": "timeseries",
   "description": "The top clusters by number of backups.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "topk by(cluster)($top_cluster_count, \n  sum by (cluster) (\n  increase(velero_backup_success_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)\n)",
     "legendFormat": "{{cluster}} - success"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, \n  sum by (cluster) (\n  increase(velero_backup_failure_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)\n)",
     "legendFormat": "{{cluster}} - failure"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, \n  sum by (cluster) (\n  increase(velero_backup_attempt_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)\n)",
     "legendFormat": "{{cluster}} - attempt"
    }
   ]
  },
  {
   "title": "Top clusters by restores / $__interval",
   "type": "timeseries",
   "description": "Top clusters by number of restores.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "topk by(cluster)($top_cluster_count, \n  sum by (cluster) (\n  increase(velero_restore_success_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)\n)",
     "legendFormat": "{{cluster}} - success"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, \n  sum by (cluster) (\n  increase(velero_restore_failed_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)\n)",
     "legendFormat": "{{cluster}} - failure"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, \n  sum by (cluster) (\n  increase(velero_restore_attempt_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)\n)",
     "legendFormat": "{{cluster}} - attempt"
    }
   ]
  },
  {
   "title": "Top clusters by backup size",
   "type": "timeseries",
   "description": "Top clusters by size of backups.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk by(cluster)($top_cluster_count, \n  sum by (cluster) (\n  velero_backup_tarball_size_bytes{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}\n)\n)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Top clusters by volume snapshots / $__interval",
   "type": "timeseries",
   "description": "Top clusters by number of volume snapshots.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk by(cluster)($top_cluster_count, \n  sum by (cluster) (\n  increase(velero_volume_snapshot_success_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)\n)",
     "legendFormat": "{{cluster}} - success"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, \n  sum by (cluster) (\n  increase(velero_volume_snapshot_failure_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)\n)",
     "legendFormat": "{{cluster}} - failure"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, \n  sum by (cluster) (\n  increase(velero_volume_snapshot_attempt_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)\n)",
     "legendFormat": "{{cluster}} - attempt"
    }
   ]
  },
  {
   "title": "Top clusters by CSI snapshots / $__interval",
   "type": "timeseries",
   "description": "Top clusters by number of CSI snapshots.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "topk by(cluster)($top_cluster_count, \n  sum by (cluster) (\n  increase(velero_csi_snapshot_success_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)\n)",
     "legendFormat": "{{cluster}} - success"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, \n  sum by (cluster) (\n  increase(velero_csi_snapshot_failure_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)\n)",
     "legendFormat": "{{cluster}} - failure"
    },
    {
     "expr": "topk by(cluster)($top_cluster_count, \n  sum by (cluster) (\n  increase(velero_csi_snapshot_attempt_total{job=\"integrations/velero\",job=~\"$job\",cluster=~\"$cluster\"}[$__interval:] offset -$__interval)\n)\n)",
     "legendFormat": "{{cluster}} - attempt"
    }
   ]
  }
 ]
}