---
name: Pull request CI workflow

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.23'
    - run: make generate
